### PR TITLE
add example from workshop

### PR DESCRIPTION
**Pull request by hakanson**
*Issue #, if available:*

*Description of changes:*

Add examples from and link to [Cedar policy language in action](https://catalog.workshops.aws/cedar-policy-language-in-action) workshop.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by shaobo-he-aws — COMMENTED** [review]
Hi @hakanson 

Thank you for your interest and contribution to the Cedar language. The examples look great. Here are some top level comment.

1. It would be great if you can add the examples to the GitHub action so that we know future changes to Cedar won't break them.
2. There's an existing example in this repo about GitHub permission management. Are they related?

**Comment by hakanson** [comment]
1. I'll work on the GitHub action validation and add commit to my PR
2. Other that "photo app" and "git app" are generic examples, not related to that, but used in the Cedar workshop I created (and linked in README)

**Comment by shaobo-he-aws** [comment]
Thank you @hakanson. It looks good to me. Calling for more reviewers.

**Comment by shaobo-he-aws** [comment]
Btw, we may want to have just one `run.sh`. But I'm not sure if it should be addressed by this CR.

**Review by shaobo-he-aws — APPROVED** [review]

**Review by aaronjeline — APPROVED** [review]

**Pull request merged**
